# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1103, 820)
        icon = QIcon()
        icon.addFile(u":/images/112-shop.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 1071, 741))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout = QGridLayout(self.tab_3)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(self.tab_3)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(40, 30, 401, 80))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.realizar_venta_pushButton = QPushButton(self.frame_5)
        self.realizar_venta_pushButton.setObjectName(u"realizar_venta_pushButton")
        self.realizar_venta_pushButton.setGeometry(QRect(20, 10, 244, 58))
        icon1 = QIcon()
        icon1.addFile(u"../assets/images/001-cart.png", QSize(), QIcon.Normal, QIcon.Off)
        self.realizar_venta_pushButton.setIcon(icon1)
        self.realizar_venta_pushButton.setIconSize(QSize(50, 50))

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_3, "")
        self.productos_tab = QWidget()
        self.productos_tab.setObjectName(u"productos_tab")
        self.frame_2 = QFrame(self.productos_tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 10, 514, 83))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.agregar_producto_pushButton = QPushButton(self.frame_2)
        self.agregar_producto_pushButton.setObjectName(u"agregar_producto_pushButton")
        icon2 = QIcon()
        icon2.addFile(u":/images/035-clothes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.agregar_producto_pushButton.setIcon(icon2)
        self.agregar_producto_pushButton.setIconSize(QSize(50, 50))

        self.horizontalLayout.addWidget(self.agregar_producto_pushButton)

        self.eliminar_producto_pushButton_2 = QPushButton(self.frame_2)
        self.eliminar_producto_pushButton_2.setObjectName(u"eliminar_producto_pushButton_2")
        icon3 = QIcon()
        icon3.addFile(u":/images/041-clothes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.eliminar_producto_pushButton_2.setIcon(icon3)
        self.eliminar_producto_pushButton_2.setIconSize(QSize(50, 50))

        self.horizontalLayout.addWidget(self.eliminar_producto_pushButton_2)

        self.editar_producto_pushButton_3 = QPushButton(self.frame_2)
        self.editar_producto_pushButton_3.setObjectName(u"editar_producto_pushButton_3")
        self.editar_producto_pushButton_3.setMinimumSize(QSize(0, 59))
        icon4 = QIcon()
        icon4.addFile(u":/images/040-clothes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.editar_producto_pushButton_3.setIcon(icon4)
        self.editar_producto_pushButton_3.setIconSize(QSize(50, 50))

        self.horizontalLayout.addWidget(self.editar_producto_pushButton_3)

        self.frame_3 = QFrame(self.productos_tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 100, 1041, 71))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 25, 101, 21))
        self.buscar_producto_por_comboBox = QComboBox(self.frame_3)
        self.buscar_producto_por_comboBox.setObjectName(u"buscar_producto_por_comboBox")
        self.buscar_producto_por_comboBox.setGeometry(QRect(120, 21, 211, 31))
        self.termino_producto_lineEdit = QLineEdit(self.frame_3)
        self.termino_producto_lineEdit.setObjectName(u"termino_producto_lineEdit")
        self.termino_producto_lineEdit.setGeometry(QRect(350, 20, 551, 31))
        self.buscar_producto_pushButton = QPushButton(self.frame_3)
        self.buscar_producto_pushButton.setObjectName(u"buscar_producto_pushButton")
        self.buscar_producto_pushButton.setGeometry(QRect(920, 20, 101, 31))
        icon5 = QIcon()
        icon5.addFile(u":/images/003-open-book-8.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buscar_producto_pushButton.setIcon(icon5)
        self.buscar_producto_pushButton.setIconSize(QSize(25, 25))
        self.productos_listWidget = QListWidget(self.productos_tab)
        self.productos_listWidget.setObjectName(u"productos_listWidget")
        self.productos_listWidget.setGeometry(QRect(30, 190, 1001, 461))
        self.label_4 = QLabel(self.productos_tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 660, 221, 21))
        self.label_5 = QLabel(self.productos_tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(260, 660, 161, 21))
        self.tabWidget.addTab(self.productos_tab, "")
        self.ventas_tab = QWidget()
        self.ventas_tab.setObjectName(u"ventas_tab")
        self.ventas_listWidget = QListWidget(self.ventas_tab)
        self.ventas_listWidget.setObjectName(u"ventas_listWidget")
        self.ventas_listWidget.setGeometry(QRect(30, 180, 1001, 461))
        self.frame_4 = QFrame(self.ventas_tab)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(20, 80, 761, 81))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 30, 47, 41))
        font = QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.inicio_dateEdit = QDateEdit(self.frame_4)
        self.inicio_dateEdit.setObjectName(u"inicio_dateEdit")
        self.inicio_dateEdit.setGeometry(QRect(150, 30, 111, 41))
        self.inicio_dateEdit.setFont(font)
        self.label_7 = QLabel(self.frame_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 30, 47, 41))
        self.label_7.setFont(font)
        self.fin_dateEdit = QDateEdit(self.frame_4)
        self.fin_dateEdit.setObjectName(u"fin_dateEdit")
        self.fin_dateEdit.setGeometry(QRect(400, 30, 111, 41))
        self.fin_dateEdit.setFont(font)
        self.buscar_venta_pushButton = QPushButton(self.frame_4)
        self.buscar_venta_pushButton.setObjectName(u"buscar_venta_pushButton")
        self.buscar_venta_pushButton.setGeometry(QRect(590, 30, 101, 41))
        self.buscar_venta_pushButton.setIcon(icon5)
        self.buscar_venta_pushButton.setIconSize(QSize(25, 25))
        self.frame_6 = QFrame(self.ventas_tab)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(30, 10, 551, 80))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.realizar_venta_pushButton_2 = QPushButton(self.frame_6)
        self.realizar_venta_pushButton_2.setObjectName(u"realizar_venta_pushButton_2")
        self.realizar_venta_pushButton_2.setGeometry(QRect(10, 10, 244, 58))
        self.realizar_venta_pushButton_2.setIcon(icon1)
        self.realizar_venta_pushButton_2.setIconSize(QSize(50, 50))
        self.consultar_ventas_pushButton = QPushButton(self.frame_6)
        self.consultar_ventas_pushButton.setObjectName(u"consultar_ventas_pushButton")
        self.consultar_ventas_pushButton.setGeometry(QRect(290, 10, 244, 58))
        self.consultar_ventas_pushButton.setIcon(icon5)
        self.consultar_ventas_pushButton.setIconSize(QSize(50, 50))
        self.label_6 = QLabel(self.ventas_tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 660, 221, 21))
        self.label_9 = QLabel(self.ventas_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(250, 660, 161, 21))
        self.tabWidget.addTab(self.ventas_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1103, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tiendita", None))
        self.realizar_venta_pushButton.setText(QCoreApplication.translate("MainWindow", u"Realizar venta", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Realizar venta", None))
        self.agregar_producto_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar producto", None))
        self.eliminar_producto_pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Eliminar producto", None))
        self.editar_producto_pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Editar producto", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Buscar por:</span></p></body></html>", None))
        self.buscar_producto_pushButton.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Cantidad de Resultados:</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">#</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.productos_tab), QCoreApplication.translate("MainWindow", u"Productos", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Inicio:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Fin:", None))
        self.buscar_venta_pushButton.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.realizar_venta_pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Realizar venta", None))
        self.consultar_ventas_pushButton.setText(QCoreApplication.translate("MainWindow", u"Consultar ventas", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Cantidad de Resultados:</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">#</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ventas_tab), QCoreApplication.translate("MainWindow", u"Ventas", None))
    # retranslateUi

